version: "3"

services:
  redis:
    image: redis:latest
    command: redis-server --appendonly yes --requirepass redispass
    volumes:
      - ./volumes/redis:/data

  clickhouse:
    image: "yandex/clickhouse-server:latest"
    volumes:
      - "./volumes/clickhouse:/var/lib/clickhouse"
    ulimits:
      nofile:
        soft: "262144"
        hard: "262144"

  minio:
    image: minio/minio:latest
    command: server /data
    volumes:
      - ./volumes/minio:/data
    ports:
      - "9000:9000"

  api:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile-api
    volumes:
      - ./diamond_miner:/app/diamond_miner
    ports:
      - "8000:8000"
    links:
      - redis

  worker:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile-worker
    volumes:
      - ./diamond_miner:/app/diamond_miner
    links:
      - redis
      - clickhouse

  agent:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile-agent
    volumes:
      - ./diamond_miner:/app/diamond_miner
    links:
      - redis
