version: "3"

services:
  redis:
    ports:
      - "6379:6379"

  minio:
    ports:
      - "9000:9000"

  api:
    ports:
      - "8000:80"

  worker:
    build:
      args:
        DEBUG: "on"
    # environment:
    #   WORKER_DEBUG_MODE: "true"

  agent:
    build:
      args:
        DEBUG: "on"

  grafana:
    ports:
      - "3000:3000"
