version: "3"

services:
  # Web Entrypoint
  traefik:
    image: docker.io/library/traefik:2.5
    command:
      - "--api=true"
      - "--api.insecure=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.redis.address=:6379"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - "80:80"
      - "6379:6379"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      default:
        aliases:
          - "api.docker.localhost"
          - "minio.docker.localhost"
          - "minio-console.docker.localhost"

  # Control-Plane & Data-Plane
  clickhouse:
    image: ${CLICKHOUSE_IMAGE:-docker.io/yandex/clickhouse-server:21}
    ports:
      - "9000:9000"
    volumes:
      - "./configuration/clickhouse/users.d:/etc/clickhouse-server/users.d:ro"
      - "./configuration/clickhouse/init-db.sh:/docker-entrypoint-initdb.d/init\
        -db.sh"
    #   - "./volumes/clickhouse:/var/lib/clickhouse"

  redis:
    image: docker.io/library/redis:6
    command: "redis-server --requirepass redispass"
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.redis.entrypoints=redis"
      - "traefik.tcp.routers.redis.rule=HostSNI(`*`)"
    # volumes:
    #   - "./volumes/redis:/data"

  minio:
    image: docker.io/minio/minio:latest
    command: "server /data --console-address :9001"
    labels:
      - "traefik.enable=true"
      # API
      - "traefik.http.routers.minio.entrypoints=web"
      - "traefik.http.routers.minio.rule=Host(`minio.docker.localhost`)"
      - "traefik.http.routers.minio.service=minio"
      - "traefik.http.services.minio.loadbalancer.server.port=9000"
      # Console
      - "traefik.http.routers.minio-console.entrypoints=web"
      - "traefik.http.routers.minio-console.rule=Host(`minio-console.docker.loc\
        alhost`)"
      - "traefik.http.routers.minio-console.service=minio-console"
      - "traefik.http.services.minio-console.loadbalancer.server.port=9001"
    # volumes:
    #   - "./volumes/minio:/data"

    # Iris
  agent:
    build:
      context: .
      dockerfile: "./dockerfiles/iris-agent.dockerfile"
    environment:
      AGENT_CARACAL_INTEGRITY_CHECK: "false" # In order to test from Docker for Mac
      AGENT_DEBUG_MODE: "true"
      AGENT_MAX_PROBING_RATE: ${AGENT_MAX_PROBING_RATE:-100}
      AWS_S3_HOST: "http://minio.docker.localhost"
      AWS_ACCESS_KEY_ID: "minioadmin"
      AWS_SECRET_ACCESS_KEY: "minioadmin"
      REDIS_URL: "redis://default:redispass@redis"
    volumes:
      - "./iris:/app/iris:ro"
    depends_on:
      - minio
      - redis

  api:
    build:
      context: .
      dockerfile: "./dockerfiles/iris-api.dockerfile"
    environment:
      API_CORS_ALLOW_ORIGIN: "http://localhost:8081"
      API_ADMIN_USERNAME: "admin"
      API_ADMIN_EMAIL: "admin@iris.docker.localhost"
      API_ADMIN_HASHED_PASSWORD: "$$2b$$12$$DOA6t1HC4zlT/AqFgQcrzuxwcTVAV2HuyZrzxORdBDxhctmMfIbUi"
      AWS_S3_HOST: "http://minio.docker.localhost"
      AWS_ACCESS_KEY_ID: "minioadmin"
      AWS_SECRET_ACCESS_KEY: "minioadmin"
      GUNICORN_CMD_ARGS: "--workers 1"
      REDIS_URL: "redis://default:redispass@redis"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.routers.api.rule=Host(`api.docker.localhost`) &&
        PathPrefix(`/api`)"
    volumes:
      - "./iris:/app/iris:ro"
    depends_on:
      - clickhouse
      - minio
      - redis

  worker:
    build:
      context: .
      dockerfile: "./dockerfiles/iris-worker.dockerfile"
    environment:
      AWS_S3_HOST: "http://minio.docker.localhost"
      AWS_ACCESS_KEY_ID: "minioadmin"
      AWS_SECRET_ACCESS_KEY: "minioadmin"
      REDIS_URL: "redis://default:redispass@redis"
      WORKER_DEBUG_MODE: "true"
    volumes:
      - "./iris:/app/iris:ro"
    depends_on:
      - clickhouse
      - minio
      - redis
