[tool.poetry]
name = "iris"
version = "0.1.3"
description = ""
authors = ["matthieugouel <matthieu.gouel@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.6"
fastapi = "^0.60.1"
aioredis = "^1.3.1"
asgiref = "^3.2.7"
dramatiq = {extras = ["redis", "watch"], version = "^1.9.0"}
redis = "^3.5.3"
python-multipart = "^0.0.5"
aioboto3 = "^8.0.3"
uvicorn = "^0.11.5"
aiofiles = "^0.5.0"
aioch = "^0.0.2"
python-logging-loki = "^0.3.1"
starlette_exporter = "^0.4.1"

[tool.poetry.dev-dependencies]
bumpversion = "^0.6.0"
click = "^7.1.2"
flake8 = "^3.8.3"
pytest = "^5.2"
requests = "^2.24.0"
watchgod = "^0.6"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
