[tool.poetry]
name = "iris"
version = "0.10.0"
description = ""
authors = ["Matthieu Gouel <matthieu.gouel@lip6.fr>"]

[tool.poetry.dependencies]
python = "^3.8"
aioboto3 = "^8.0.3"
aioch = "^0.0.2"
aiofiles = "^0.5.0"
aioredis = "^1.3.1"
asgiref = "^3.2.7"
clickhouse-driver = "^0.2.0"
diamond-miner = {develop = true, path = "vendors/diamond-miner"}
dramatiq = {extras = ["redis", "watch"], version = "^1.9.0"}
fastapi = "^0.60.1"
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
python-logging-loki = "^0.3.1"
python-multipart = "^0.0.5"
redis = "^3.5.3"
starlette_exporter = "^0.4.1"
tenacity = "^6.2.0"
uvicorn = "^0.11.5"
python-jose = {extras = ["cryptography"], version = "^3.2.0"}
typer = "^0.3.2"
rich = "^10.1.0"
pycaracal = "^0.4.20"

[tool.poetry.dev-dependencies]
black = {version = "^21.4b2", allow-prereleases = true}
boto3-stubs = "^1.17.60"
bumpversion = "^0.6.0"
click = "^7.1.2"
coverage = "^5.2.1"
flake8 = "^3.8.3"
mypy = "^0.812"
pre-commit = "^2.11.1"
pytest = "^6.0.0"
pytest-asyncio = "^0.15"
pytest-cov = "^2.10.0"
types-aiofiles = "^0.1.2"

[tool.pytest.ini_options]
addopts = "--ignore volumes --cov=iris --cov-report term-missing -vvs"
filterwarnings = [
    "ignore::DeprecationWarning:aiofiles.*:",
    "ignore::DeprecationWarning:urllib3.*:",
    "ignore::DeprecationWarning:aiohttp.*:",
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
iris-standalone = 'iris.standalone.main:app'
