name: Docker

on:
  push:
    tags: [ 'v*' ]
# Build only on tags for now to reduce private GitHub CI credits usage.
#    branches: [ 'main' ]
#  pull_request:
#    branches: [ 'main' ]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        image:
          - iris-agent
          - iris-api
          - iris-worker
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: registry.gitlab.com/dioptra-io/iris/${{ matrix.image }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Login to Docker registry
        uses: docker/login-action@v1
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.GITLAB_REGISTRY_USERNAME }}
          password: ${{ secrets.GITLAB_REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./dockerfiles/${{ matrix.image }}.dockerfile
          platforms: linux/amd64
          # platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
