name: Docker

on:
  push:
    # Build only on main and production branch commits for now
    # to reduce private GitHub CI credits usage.
    branches:
      - main
      - production
    # pull_request:
    #   branches: [ 'main' ]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        image:
          - iris-agent
          - iris-api
          - iris-worker
    steps:
      - uses: actions/checkout@v2
      - uses: dioptra-io/publish-docker-action@v1.1
        with:
          file: ./dockerfiles/${{ matrix.image }}.dockerfile
          image: dioptra-io/iris/${{ matrix.image }}
          password: ${{ secrets.GITHUB_TOKEN }}
          # platforms: linux/amd64,linux/arm64
