name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      clickhouse:
        image: yandex/clickhouse-server
        ports: ['8123:8123', '9000:9000']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install clickhouse-client and zstd
        run: |
          sudo apt install --yes apt-transport-https ca-certificates dirmngr
          sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv E0C56BD4
          echo "deb https://repo.clickhouse.tech/deb/stable/ main/" | sudo tee \
              /etc/apt/sources.list.d/clickhouse.list
          sudo apt update
          sudo apt install --yes clickhouse-client zstd
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --extras "agent api standalone worker"
      - name: Tests
        run: poetry run pytest --cov-report xml tests
      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
